spring.application.name=RestCrudApp

# JDBC properties

spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Number of elements shown per page in Spring Data REST endpoints
spring.data.rest.default-page-size=3